version: "3.9"
services:
    flask:
        container_name: "flask_${CONTAINER_NAME}"
        restart: always
        build: ./flask
        cap_add: 
            - SYS_ADMIN
            - DAC_READ_SEARCH
        privileged: true
        volumes:
            - ./volume/flask:/home/project/flask
        ports:
            - "${EXPOSE_SSH_PORT}:22"
        # 此command 可移至dockerfile CMD/entrypoint 執行
        # command: bash -c "mount -a && gunicorn -w 1 -b :8000 Run_server:app"
        command: bash -c "service ssh start && gunicorn -w 1 -b :8000 --chdir ./python/flask Run_server:app"

    nginx:
        container_name: "nginx_${CONTAINER_NAME}"
        restart: always
        build: ./nginx
        volumes:
            - ./volume/nginx/:/usr/share/nginx/
        ports: 
            - "${EXPOSE_nginx_PORT}:80"
        depends_on: 
            - flask